name: dotnet package

on:
  push:
    branches: [ "master", "feature" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Display dotnet version
      run: dotnet --version
    - name: Restore dependencies
      run: dotnet restore StrategyLab2/
    - name: Build
      run: dotnet build StrategyLab2/ --no-restore
    - name: Test
      run: dotnet test Tests/ --no-build --verbosity normal
